import "../index.css";
import WebFont from "webfontloader";

// Load the Montserrat font
WebFont.load({
  google: {
    families: ["Montserrat:300,400,600"],
  },
});

const metadata = {
  title: "John Doe | Mern Stack Developer",
  description: "Generated by create react app",
};

const Layout = ({ children }) => {
  return (
    <div style={{ fontFamily: "Montserrat, sans-serif" }}>
      {children}
    </div>
  );
};

export default Layout;
export { metadata };
